owner: dragonjuno
repo: ovn-uptime

sites:
  - name: 오븐 웹사이트
    url: https://artovn.com
  - name: 오븐 이미지 서버
    url: https://cdn.ovn.one
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 400

status-website:
  name: 시스템 상태 현황
  cname: "status.ovn.one"
  theme: light
  i18n:
    activeIncidents: 현재 발생 중인 장애
    allSystemsOperational: 모든 시스템이 정상 작동 중입니다
    incidentReport: 장애 리포트
    activeIncidentSummary: "$OPENED에 시작됨 ($POSTS개의 업데이트)"
    liveStatus: 실시간 상태
    overallUptime: "전체 가동률: $UPTIME"
    degradedPerformance: 성능 저하
    completeOutage: 전체 중단
    partialOutage: 부분 중단
    majorOutage: 대규모 장애
    footer: 본 페이지는 [Upptime]($REPO)으로 자동 구동됩니다.
